
### Sign-Up
POST http://localhost:3000/api/signup 
Content-Type: application/json

{ "password":"123456", "name":"hsj2", "email":"asd23@asdasd.asd" }

### Sign-In
# @name getJWT
POST http://localhost:3000/api/signin
Content-Type: application/json

{ "password":"123456", "email":"asd2@asdasd.asd" }

### 내정보 조회
GET http://localhost:3000/api/signin/me
Content-Type: application/json
Authorization: Bearer {{getJWT.response.body.accesstoken}}

### CREATE 상품생성
POST http://localhost:3000/api/product
Content-Type: application/json
Authorization: Bearer {{getJWT.response.body.accesstoken}}

{ "productName":"콜라32", "productComments":"제로입니다3", "price":202220 }

### READ 상품 목록 조회
GET http://localhost:3000/api/products
Content-Type: application/json

### READ 상품 상세 조회
GET http://localhost:3000/api/product/17
Content-Type: application/json


### UPDATE 상품 수정
PATCH http://localhost:3000/api/product/15
Content-Type: application/json
Authorization: Bearer {{getJWT.response.body.accesstoken}}

{ "productName":"콜라23", "productComments":"제로입니다2", "price":2202220 }

### DELETE 상품 삭제
DELETE http://localhost:3000/api/product/15
Content-Type: application/json
Authorization: Bearer {{getJWT.response.body.accesstoken}}
